### ISSUE TITLE
Use sidebar ID in `dynamic_sidebar` rather than sidebar name

### ISSUE THREAD

**Issue by ernilambar** [joedolson/milky-way#10]
We should never use sidebar name in `dynamic_sidebar()`.

`dynamic_sidebar( 'Front Page Content - Left' )`

This wont work when theme is used in other locale.

Also `ps6` and `ps7`, should be `mw6` and `mw7`.

**Comment by joedolson** [comment]
Fixed in https://github.com/joedolson/milky-way/commit/2e12a8d18bf73d499622b1105a117d06da71edec (widget IDs changed previously.)
