### ISSUE TITLE
Custom function for archive title

### ISSUE THREAD

**Issue by ernilambar** [joedolson/milky-way#12]
`milky_way_archive_title()`

Since WP already has `the_archive_title()` for archive title, I am fairly sure custom function for archive title wont be allowed in the theme review. We could use `get_the_archive_title` filter for customizing archive title.

**Comment by joedolson** [comment]
Closing; switched to filter in https://github.com/joedolson/milky-way/commit/5b84b4dadd501e6fb6fef3207512c82a7a0e7e56
