### ISSUE TITLE
Use filter for add extra class in body

### ISSUE THREAD

**Issue by ernilambar** [joedolson/milky-way#15]
`$class = ( !is_front_page() ) ? 'not-home' : '';`
`body_class( $class );`

Recommended approach is to use filter rather than passing class directly. https://developer.wordpress.org/reference/hooks/body_class/

**Comment by joedolson** [comment]
Resolved in https://github.com/joedolson/milky-way/commit/a68886f6462857fdb5e123cb759bee4002ece0d0 Thanks!
