### ISSUE TITLE
Site title and tagline in Customizer does not reflect in live preview

### ISSUE THREAD

**Issue by ernilambar** [joedolson/milky-way#17]
`$( '#site-title a' ).html( newval );` -> `$( '.site-title a' ).html( newval );` fix the issue of site title.

Similar code should be there for site tagline.

**Comment by joedolson** [comment]
Resolved in https://github.com/joedolson/milky-way/commit/9f992a19172396d4c62ef60d35afb28f31fcf74a Thanks!
