### ISSUE TITLE
Website field design is not same like other text field in comment form

### ISSUE THREAD

**Issue by ernilambar** [joedolson/milky-way#18]
Comment form in single
http://prnt.sc/bywsya

Website field in not same with other text field. Also focus effect is not same.

Note: Tested in Firefox

**Comment by joedolson** [comment]
What do you mean by "not same with other text field" - what is the difference? I'm also not seeing a difference in the focus effect; can you add more detail?

**Comment by ernilambar** [comment]
Have you reproduced like this? http://prnt.sc/c0rfcb I am clearly seeing difference. I am not sure if this is my browser issue.

**Comment by joedolson** [comment]
I see - no, I'm not seeing that. Is it possibly coming from a plug-in or Firefox add-on?

**Comment by ernilambar** [comment]
It seems good in Chrome. But I am still getting similar when all addon disabled. Lets close this for now, if anything new later then we can reopen issue.
