### ISSUE TITLE
Prefixing for style handle

### ISSUE THREAD

**Issue by ernilambar** [joedolson/milky-way#23]
```
wp_register_style( 'heading', 'https://fonts.googleapis.com/css?family=Domine:400,700' );
wp_register_style( 'reset', get_template_directory_uri() . '/css/reset.css' );
```

Since these styles are specific to our theme, we need to prefix style handle. Similar for others like `menu`, `font`, etc.

**Comment by joedolson** [comment]
Fixed in https://github.com/joedolson/milky-way/commit/964ca99b6fceb80e58be29c5952404568826bfc1
