### ISSUE TITLE
Do we need `milky_way_custom_background` function?

### ISSUE THREAD

**Issue by ernilambar** [joedolson/milky-way#24]
Do we need `milky_way_custom_background` function? I believe custom background styles are automatically added by WP core.
Currently when image is added as Background Image, in the HTML markup:

```
<style type='text/css'>
    body { background: #e6e6e6 url(http://staging.dev/wp-content/uploads/2016/07/wcktm-main-banner.png) no-repeat stretch; }
</style>
    <style type="text/css" id="custom-background-css">
body.custom-background { background-image: url('http://staging.dev/wp-content/uploads/2016/07/wcktm-main-banner.png'); background-repeat: no-repeat; background-position: top left; background-attachment: fixed; }
</style>
```

One from our code. And another from WP core.

**Comment by joedolson** [comment]
Do you have a reference for the function where the core custom background CSS is built? I believe I had a reason for doing it this way, but don't recall now. (I can find the reference; but if you already know it, that would save some time.)

**Comment by ernilambar** [comment]
That code comes from `_custom_background_cb` function callback, which is default callback. See https://codex.wordpress.org/Custom_Backgrounds#Adding_Theme_Support

Function in trac: https://core.trac.wordpress.org/browser/trunk/src/wp-includes/theme.php#L1359

**Comment by joedolson** [comment]
That's right; what I don't like is that the core function doesn't provide a color fallback if an image is selected but doesn't load. However, what I should probably do is submit a patch to core for that issue, rather than duplicating it in the theme.

**Comment by joedolson** [comment]
On testing, looks like the core function does provide the color fallback, so no problem. Will remove function.

**Comment by joedolson** [comment]
Removed in https://github.com/joedolson/milky-way/commit/5ebd9e594d680f264cbc9783f8b6c98ead9a1176
