### ISSUE TITLE
Avoid HTML tag in translatable strings

### ISSUE THREAD

**Issue by ernilambar** [joedolson/milky-way#26]
`$post_link = wpautop( sprintf( __( '<a href="%s" rel="bookmark">View untitled post</a>', 'milky-way' ), esc_url( get_the_permalink() ) ) );`

In translation, it would be like, `'<a href="%s" rel="bookmark">View untitled post</a>`.

We should always try to avoid HTML tag in translation strings because there would be high chance that translator translating those incorrectly.

Since this is not high priority, we could audit whole theme for this after theme is live?

**Comment by joedolson** [comment]
Resolved in https://github.com/joedolson/milky-way/commit/ef45017e74e796ef17ec786fbc3dbc66d2dc2682

**Comment by joedolson** [comment]
I'd rather resolve any instances of this sooner rather than later, since I'd prefer not to change translatable strings unless absolutely necessary after release.
