### ISSUE TITLE
Implementing `post_class()`

### ISSUE THREAD

**Issue by ernilambar** [joedolson/milky-way#27]
We need to audit theme for proper implementation of `<?php post_class(); ?>`. https://developer.wordpress.org/reference/functions/post_class/

Plugins may have been dependent on the classes generated by `post_class()`. Without its proper implementation, there will be conflict and incompatibility with plugins.

**Comment by joedolson** [comment]
If you have any specific concerns, please raise them as individual issues. Thanks!
