### ISSUE TITLE
Image hs-2005-01-a-full_jpg.jpg could be avoided to bundle in the theme

### ISSUE THREAD

**Issue by ernilambar** [joedolson/milky-way#28]
Image `hs-2005-01-a-full_jpg.jpg` could be removed from the theme as we have already kept direct link for the resource. 3 MB size could be reduced from the zip of the theme. Thoughts?

**Comment by joedolson** [comment]
Removed https://github.com/joedolson/milky-way/commit/81b0d168f8de324bca0992a488efeb25406a7d50
