### ISSUE TITLE
Format value where post format is false

### ISSUE THREAD

**Issue by ernilambar** [joedolson/milky-way#3]
`single.php`

```
if ( $format === false ) {
    $format = 'format';
}
```

If `$format` is `false`, may be `$format` should be `''` or `null`.
Currently, if `$format` is false,
`get_template_part( 'partials/format', 'format' );`
Then WP will look for `partials/format-format.php` template which does not exist.

**Comment by ernilambar** [comment]
Similar issue in `index.php` https://github.com/joedolson/milky-way/blob/master/index.php#L10

**Comment by joedolson** [comment]
Resolved in https://github.com/joedolson/milky-way/commit/44eae4a76c8c391becb05877d39c1d22c342809b

**Comment by joedolson** [comment]
(Suppose I really should have opened this, _then_ resolved it. Eh, whatever.)
