### ISSUE TITLE
Posts navigation in single.php

### ISSUE THREAD

**Issue by ernilambar** [joedolson/milky-way#34]
Is `posts_nav_link()` working? Something wrong I guess. http://themes.joedolson.com/milkyway/2016/02/26/hello-world/ There is no next or prev links in the bottom.

We could use `the_post_navigation()` for posts navigation in single.

**Comment by joedolson** [comment]
Fixed in https://github.com/joedolson/milky-way/commit/67f0f5478bb21594979bcb39fd77b49c910be1d6
