### ISSUE TITLE
Remove back compat shim for title

### ISSUE THREAD

**Issue by ernilambar** [joedolson/milky-way#9]
This code could be removed because we need not provide back compat for more than 3 major WP versions. `add_theme_support( 'title-tag' );` is available since `WP 4.1`.

```
if ( ! function_exists( '_wp_render_title_tag' ) ) {
    function milky_way_render_title() {
        ?>
        <title><?php wp_title( ' &raquo; ', true, 'right' ); ?></title>
        <?php
    }
    add_action( 'wp_head', 'milky_way_render_title' );
}
```

**Comment by joedolson** [comment]
Definitely one of those wacky issues that happens with 6 months+ between submission and review...

Resolved in https://github.com/joedolson/milky-way/commit/78d4aceec455eeebfd1caea42df7c0b809bbe0ea
